import { describe, expect, it } from "vitest";
import { parseLockfile } from "../../src/parsers/index.js";

// ---------------------------------------------------------------------------
// Fixtures — trimmed lockfile snippets
// ---------------------------------------------------------------------------

const PACKAGE_LOCK_V3 = JSON.stringify({
  packages: {
    "": { version: "1.0.0" },
    "node_modules/express": { version: "4.18.2" },
    "node_modules/@scope/pkg": { version: "2.0.0" },
  },
});

const PACKAGE_LOCK_V1 = JSON.stringify({
  dependencies: {
    express: { version: "4.18.2" },
    lodash: {
      version: "4.17.21",
      dependencies: {
        nested: { version: "1.0.0" },
      },
    },
  },
});

const YARN_LOCK = `# THIS IS AN AUTOGENERATED FILE
# yarn lockfile v1

express@^4.18.0:
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz"

@babel/core@^7.0.0:
  version "7.23.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.23.0.tgz"
`;

const PNPM_LOCK_V9 = `lockfileVersion: '9.0'

packages:
  express@4.18.2:
    resolution: {integrity: sha512-xxx}
  @scope/pkg@1.0.0:
    resolution: {integrity: sha512-yyy}
`;

const PNPM_LOCK_V6 = `lockfileVersion: 5.4

packages:
  /express/4.18.2:
    resolution: {integrity: sha512-xxx}
  /@scope/pkg/2.0.0:
    resolution: {integrity: sha512-yyy}
`;

const REQUIREMENTS_TXT = `# a comment
-r other.txt
--index-url https://pypi.org/simple
requests==2.31.0  # inline comment
Flask==3.0.0
`;

const CARGO_LOCK = `[[package]]
name = "serde"
version = "1.0.188"

[[package]]
name = "tokio"
version = "1.32.0"
`;

const GO_SUM = `github.com/gin-gonic/gin v1.9.1 h1:abc=
github.com/gin-gonic/gin v1.9.1/go.mod h1:def=
github.com/stretchr/testify v1.8.4 h1:ghi=
`;

const GEMFILE_LOCK = `GEM
  remote: https://rubygems.org/
  specs:
    rails (7.0.3.1)
      actioncable (= 7.0.3.1)
      actionmailbox (= 7.0.3.1)
      actionmailer (= 7.0.3.1)
    actioncable (7.0.3.1)
      actionpack (= 7.0.3.1)
    puma (5.6.5)
      nio4r (~> 2.0)
    nio4r (2.5.9)

PLATFORMS
  x86_64-darwin-20

DEPENDENCIES
  rails (~> 7.0.3)
  puma (~> 5.0)

RUBY VERSION
   ruby 3.1.0p0

BUNDLED WITH
   2.3.14
`;

// ---------------------------------------------------------------------------
// parseLockfile — dispatch
// ---------------------------------------------------------------------------

describe("parseLockfile", () => {
  it("returns null for unrecognised filenames", () => {
    expect(parseLockfile("unknown.txt", "")).toBeNull();
  });

  it("strips path prefix and matches basename", () => {
    expect(parseLockfile("/app/project/unknown.txt", "")).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// package-lock.json
// ---------------------------------------------------------------------------

describe("package-lock.json", () => {
  it("parses v2/v3 packages with regular and scoped names", () => {
    const deps = parseLockfile("package-lock.json", PACKAGE_LOCK_V3);
    expect(deps).toHaveLength(2);
    expect(deps).toContainEqual({ name: "express", version: "4.18.2", ecosystem: "npm" });
    expect(deps).toContainEqual({ name: "@scope/pkg", version: "2.0.0", ecosystem: "npm" });
  });

  it("skips root entry and entries without a version", () => {
    const content = JSON.stringify({
      packages: {
        "": {},
        "node_modules/foo": {},
        "node_modules/bar": { version: "1.0.0" },
      },
    });
    const deps = parseLockfile("package-lock.json", content);
    expect(deps).toHaveLength(1);
    expect(deps).toContainEqual({ name: "bar", version: "1.0.0", ecosystem: "npm" });
  });

  it("parses v1 legacy format with nested dependencies", () => {
    const deps = parseLockfile("package-lock.json", PACKAGE_LOCK_V1);
    expect(deps).toHaveLength(3);
    expect(deps).toContainEqual({ name: "express", version: "4.18.2", ecosystem: "npm" });
    expect(deps).toContainEqual({ name: "lodash", version: "4.17.21", ecosystem: "npm" });
    expect(deps).toContainEqual({ name: "nested", version: "1.0.0", ecosystem: "npm" });
  });

  it("returns empty array for invalid JSON", () => {
    expect(parseLockfile("package-lock.json", "not json")).toEqual([]);
  });

  it("returns empty array when neither packages nor dependencies exist", () => {
    const content = JSON.stringify({ name: "test", version: "1.0.0" });
    expect(parseLockfile("package-lock.json", content)).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// yarn.lock
// ---------------------------------------------------------------------------

describe("yarn.lock", () => {
  it("parses regular and scoped packages, skipping comments", () => {
    const deps = parseLockfile("yarn.lock", YARN_LOCK);
    expect(deps).toHaveLength(2);
    expect(deps).toContainEqual({ name: "express", version: "4.18.2", ecosystem: "npm" });
    expect(deps).toContainEqual({ name: "@babel/core", version: "7.23.0", ecosystem: "npm" });
  });
});

// ---------------------------------------------------------------------------
// pnpm-lock.yaml
// ---------------------------------------------------------------------------

describe("pnpm-lock.yaml", () => {
  it("parses v9 format (name@version)", () => {
    const deps = parseLockfile("pnpm-lock.yaml", PNPM_LOCK_V9);
    expect(deps).toHaveLength(2);
    expect(deps).toContainEqual({ name: "express", version: "4.18.2", ecosystem: "npm" });
    expect(deps).toContainEqual({ name: "@scope/pkg", version: "1.0.0", ecosystem: "npm" });
  });

  it("parses v6 format (/name/version)", () => {
    const deps = parseLockfile("pnpm-lock.yaml", PNPM_LOCK_V6);
    expect(deps).toHaveLength(2);
    expect(deps).toContainEqual({ name: "express", version: "4.18.2", ecosystem: "npm" });
    expect(deps).toContainEqual({ name: "@scope/pkg", version: "2.0.0", ecosystem: "npm" });
  });
});

// ---------------------------------------------------------------------------
// requirements.txt
// ---------------------------------------------------------------------------

describe("requirements.txt", () => {
  it("parses pinned deps, lowercases names, skips comments and flags", () => {
    const deps = parseLockfile("requirements.txt", REQUIREMENTS_TXT);
    expect(deps).toHaveLength(2);
    expect(deps).toContainEqual({ name: "requests", version: "2.31.0", ecosystem: "pypi" });
    expect(deps).toContainEqual({ name: "flask", version: "3.0.0", ecosystem: "pypi" });
  });
});

// ---------------------------------------------------------------------------
// Cargo.lock
// ---------------------------------------------------------------------------

describe("Cargo.lock", () => {
  it("parses [[package]] blocks", () => {
    const deps = parseLockfile("Cargo.lock", CARGO_LOCK);
    expect(deps).toHaveLength(2);
    expect(deps).toContainEqual({ name: "serde", version: "1.0.188", ecosystem: "cargo" });
    expect(deps).toContainEqual({ name: "tokio", version: "1.32.0", ecosystem: "cargo" });
  });

  it("captures last package when file has no trailing section", () => {
    const content = `[[package]]\nname = "only"\nversion = "1.0.0"`;
    const deps = parseLockfile("Cargo.lock", content);
    expect(deps).toHaveLength(1);
    expect(deps).toContainEqual({ name: "only", version: "1.0.0", ecosystem: "cargo" });
  });
});

// ---------------------------------------------------------------------------
// go.sum
// ---------------------------------------------------------------------------

describe("go.sum", () => {
  it("parses modules and deduplicates go.mod entries", () => {
    const deps = parseLockfile("go.sum", GO_SUM);
    expect(deps).toHaveLength(2);
    expect(deps).toContainEqual({ name: "github.com/gin-gonic/gin", version: "1.9.1", ecosystem: "go" });
    expect(deps).toContainEqual({ name: "github.com/stretchr/testify", version: "1.8.4", ecosystem: "go" });
  });
});

// ---------------------------------------------------------------------------
// Gemfile.lock
// ---------------------------------------------------------------------------

describe("Gemfile.lock", () => {
  it("parses gems from specs section, skipping dependencies", () => {
    const deps = parseLockfile("Gemfile.lock", GEMFILE_LOCK);
    expect(deps).toHaveLength(4);
    expect(deps).toContainEqual({ name: "rails", version: "7.0.3.1", ecosystem: "rubygems" });
    expect(deps).toContainEqual({ name: "actioncable", version: "7.0.3.1", ecosystem: "rubygems" });
    expect(deps).toContainEqual({ name: "puma", version: "5.6.5", ecosystem: "rubygems" });
    expect(deps).toContainEqual({ name: "nio4r", version: "2.5.9", ecosystem: "rubygems" });
  });

  it("handles gems with version constraints using = prefix", () => {
    const content = `GEM
  remote: https://rubygems.org/
  specs:
    rails (7.0.3.1)
      actioncable (= 7.0.3.1)
    actioncable (7.0.3.1)
`;
    const deps = parseLockfile("Gemfile.lock", content);
    expect(deps).toHaveLength(2);
    expect(deps).toContainEqual({ name: "rails", version: "7.0.3.1", ecosystem: "rubygems" });
    expect(deps).toContainEqual({ name: "actioncable", version: "7.0.3.1", ecosystem: "rubygems" });
  });

  it("stops parsing at PLATFORMS section", () => {
    const content = `GEM
  remote: https://rubygems.org/
  specs:
    rails (7.0.3.1)

PLATFORMS
  x86_64-darwin-20
`;
    const deps = parseLockfile("Gemfile.lock", content);
    expect(deps).toHaveLength(1);
    expect(deps).toContainEqual({ name: "rails", version: "7.0.3.1", ecosystem: "rubygems" });
  });

  it("handles gems with hyphens and underscores in names", () => {
    const content = `GEM
  remote: https://rubygems.org/
  specs:
    sprockets-rails (3.4.2)
    tzinfo-data (1.2023.3)
    web_console (4.2.0)
`;
    const deps = parseLockfile("Gemfile.lock", content);
    expect(deps).toHaveLength(3);
    expect(deps).toContainEqual({
      name: "sprockets-rails",
      version: "3.4.2",
      ecosystem: "rubygems",
    });
    expect(deps).toContainEqual({
      name: "tzinfo-data",
      version: "1.2023.3",
      ecosystem: "rubygems",
    });
    expect(deps).toContainEqual({ name: "web_console", version: "4.2.0", ecosystem: "rubygems" });
  });

  it("returns empty array when no specs section exists", () => {
    const content = `GEM
  remote: https://rubygems.org/

PLATFORMS
  x86_64-darwin-20
`;
    const deps = parseLockfile("Gemfile.lock", content);
    expect(deps).toEqual([]);
  });

  it("ignores GIT section and only parses GEM specs", () => {
    const content = `GIT
  remote: https://github.com/heartcombo/devise.git
  revision: c9e655e13253dc53e3c0981a8345f134bcda1fc5
  branch: main
  specs:
    devise (5.0.2)
      bcrypt (~> 3.0)

GEM
  remote: https://rubygems.org/
  specs:
    rails (7.1.5.2)
      actionpack (= 7.1.5.2)
    actionpack (7.1.5.2)
`;
    const deps = parseLockfile("Gemfile.lock", content);
    // Should only parse GEM section, not GIT section
    expect(deps).toHaveLength(2);
    expect(deps).toContainEqual({ name: "rails", version: "7.1.5.2", ecosystem: "rubygems" });
    expect(deps).toContainEqual({ name: "actionpack", version: "7.1.5.2", ecosystem: "rubygems" });
  });

  it("normalizes platform-qualified gem versions", () => {
    const content = `GEM
  remote: https://rubygems.org/
  specs:
    nokogiri (1.14.2-x86_64-darwin)
    nokogiri (1.14.2-aarch64-darwin)
    nokogiri (1.14.2-universal-darwin)
    ffi (1.15.5-x64_mingw32)
    nio4r (2.5.8-java)
`;
    const deps = parseLockfile("Gemfile.lock", content);
    expect(deps).toHaveLength(5);
    expect(deps).toContainEqual({ name: "nokogiri", version: "1.14.2", ecosystem: "rubygems" });
    expect(deps).toContainEqual({ name: "ffi", version: "1.15.5", ecosystem: "rubygems" });
    expect(deps).toContainEqual({ name: "nio4r", version: "2.5.8", ecosystem: "rubygems" });
  });

  it("preserves prerelease when stripping platform suffix", () => {
    const content = `GEM
  remote: https://rubygems.org/
  specs:
    rails (7.1.0-beta.1-x86_64-darwin)
`;
    const deps = parseLockfile("Gemfile.lock", content);
    expect(deps).toContainEqual({ name: "rails", version: "7.1.0-beta.1", ecosystem: "rubygems" });
  });

  it("preserves legitimate prerelease identifiers", () => {
    const content = `GEM
  remote: https://rubygems.org/
  specs:
    rails (7.1.0-beta.1)
    devise (5.0.0-rc1)
`;
    const deps = parseLockfile("Gemfile.lock", content);
    expect(deps).toHaveLength(2);
    expect(deps).toContainEqual({ name: "rails", version: "7.1.0-beta.1", ecosystem: "rubygems" });
    expect(deps).toContainEqual({ name: "devise", version: "5.0.0-rc1", ecosystem: "rubygems" });
  });

  it("handles gem names with uppercase letters and dots", () => {
    const content = `GEM
  remote: https://rubygems.org/
  specs:
    RubyInline (3.12.5)
    net-ssh (7.0.1)
    i18n (1.12.0)
`;
    const deps = parseLockfile("Gemfile.lock", content);
    expect(deps).toHaveLength(3);
    expect(deps).toContainEqual({ name: "RubyInline", version: "3.12.5", ecosystem: "rubygems" });
    expect(deps).toContainEqual({ name: "net-ssh", version: "7.0.1", ecosystem: "rubygems" });
    expect(deps).toContainEqual({ name: "i18n", version: "1.12.0", ecosystem: "rubygems" });
  });
});
